name: Deploy to EC2 Docker

on:
  workflow_run:
    workflows: ["Publicar imagen Docker"]   # nombre EXACTO del docker.yml
    types: [completed]

  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Add SSH Key
      run: |
        echo "${{ secrets.EC2_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Deploy Container
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          docker pull ${{ secrets.DOCKER_IMAGE }}
          docker stop app || true
          docker rm app || true
          docker run -d --name app -p 80:8080 ${{ secrets.DOCKER_IMAGE }}
        EOF

